version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/lachs"
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo"
    directory: "/crates/lachs_derive"
    schedule:
      interval: "daily"
